# Generated by Django 3.1.7 on 2021-03-06 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('org', models.PositiveSmallIntegerField(choices=[(0, 'LexisNexis'), (1, 'Elsevier'), (2, 'Exhibitions'), (3, 'RELX'), (4, 'External')], default=0)),
                ('timezone', models.PositiveSmallIntegerField(choices=[(0, 'UTC-12'), (1, 'UTC-11'), (2, 'UTC-10'), (3, 'UTC-9'), (4, 'UTC-8'), (5, 'UTC-7'), (6, 'UTC-6'), (7, 'UTC-5'), (8, 'UTC-4'), (9, 'UTC-3'), (10, 'UTC-2'), (11, 'UTC-1'), (12, 'UTC+0'), (13, 'UTC+1'), (14, 'UTC+2'), (15, 'UTC+3'), (16, 'UTC+4'), (17, 'UTC+5'), (18, 'UTC+6'), (19, 'UTC+7'), (20, 'UTC+8'), (21, 'UTC+9'), (22, 'UTC+10'), (23, 'UTC+11')], default=12)),
                ('speaker_bio', models.TextField(blank=True)),
                ('is_attendee', models.BooleanField(default=True)),
                ('is_reviewer', models.BooleanField(default=False)),
                ('is_speaker', models.BooleanField(default=False)),
                ('is_organizer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
