# Generated by Django 3.1.7 on 2021-03-06 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='speaker_avatar',
            field=models.FileField(blank=True, upload_to='avatars'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.PositiveSmallIntegerField(choices=[(0, 'Long Form'), (1, 'Short Form'), (3, 'Workshop'), (4, 'Poster')], default=0)),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=128)),
                ('is_accepted', models.BooleanField(default=False)),
                ('pres_slides', models.FileField(blank=True, upload_to='slides')),
                ('pres_videos', models.FileField(blank=True, upload_to='videos')),
                ('co_authors', models.ManyToManyField(to='apps.Attendee')),
                ('primary_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendee', to='apps.attendee')),
            ],
        ),
    ]
