# Generated by Django 3.1.7 on 2021-03-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210306_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='co_authors',
            field=models.ManyToManyField(blank=True, to='apps.Attendee'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='primary_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_author', to='apps.attendee'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 'Unscored'), (1, 'Strong Accept'), (2, 'Accept'), (3, 'Maybe Accept'), (4, 'Reject')], default=0)),
                ('comments', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='apps.paper')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_name', to='apps.attendee')),
            ],
        ),
    ]
