# Generated by Django 3.1.7 on 2021-03-06 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20210306_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='paper',
            name='submitted_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
