# Generated by Django 3.1.7 on 2021-03-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20210306_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='email',
            field=models.EmailField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='org',
            field=models.CharField(choices=[('LexisNexis', 'LexisNexis'), ('Elsevier', 'Elsevier'), ('Exhibitions', 'Exhibitions'), ('RELX', 'RELX'), ('External', 'External')], default=0, max_length=32),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='timezone',
            field=models.CharField(choices=[('UTC-12', 'UTC-12'), ('UTC-11', 'UTC-11'), ('UTC-10', 'UTC-10'), ('UTC-9', 'UTC-9'), ('UTC-8', 'UTC-8'), ('UTC-7', 'UTC-7'), ('UTC-6', 'UTC-6'), ('UTC-5', 'UTC-5'), ('UTC-4', 'UTC-4'), ('UTC-3', 'UTC-3'), ('UTC-2', 'UTC-2'), ('UTC-1', 'UTC-1'), ('UTC+0', 'UTC+0'), ('UTC+1', 'UTC+1'), ('UTC+2', 'UTC+2'), ('UTC+3', 'UTC+3'), ('UTC+4', 'UTC+4'), ('UTC+5', 'UTC+5'), ('UTC+6', 'UTC+6'), ('UTC+7', 'UTC+7'), ('UTC+8', 'UTC+8'), ('UTC+9', 'UTC+9'), ('UTC+10', 'UTC+10'), ('UTC+11', 'UTC+11')], default=12, max_length=32),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('Long Form', 'Long Form'), ('Short Form', 'Short Form'), ('Workshop', 'Workshop'), ('Poster', 'Poster')], default=0, max_length=16),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.CharField(choices=[('--', '--'), ('Strong Accept', 'Strong Accept'), ('Accept', 'Accept'), ('Maybe Accept', 'Maybe Accept'), ('Reject', 'Reject')], default=0, max_length=16),
        ),
    ]
