# Generated by Django 3.1.7 on 2021-03-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20210319_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='utc_offset',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
