# Generated by Django 3.1.7 on 2021-03-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_delete_papertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type_name', models.CharField(max_length=16)),
            ],
        ),
    ]
