# Generated by Django 3.1.7 on 2021-03-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_papertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='themes',
            field=models.ManyToManyField(to='apps.PaperTheme'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paper_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_type', to='apps.papertype'),
        ),
    ]
