# Generated by Django 3.1.7 on 2021-03-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_review_reason_if_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='accept_speaker_invite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='extra_long_paper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='publish_full_paper_in_ssrn',
            field=models.BooleanField(default=False),
        ),
    ]
