# Generated by Django 3.1.7 on 2021-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_paper_publish_abstract_in_ssrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='speaker_avatar',
            field=models.ImageField(blank=True, upload_to='avatars'),
        ),
    ]
