# Generated by Django 3.1.7 on 2021-03-27 01:26

import apps.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20210322_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='speaker_avatar',
            field=models.ImageField(blank=True, upload_to=apps.models._content_file_name),
        ),
        migrations.AlterField(
            model_name='papertheme',
            name='paper_theme',
            field=models.CharField(max_length=64),
        ),
    ]
