# Generated by Django 3.1.7 on 2021-04-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_seq',
            field=models.IntegerField(default=0),
        ),
    ]
